name: dartypod
description: A minimal Service Locator with compile-time safe provider references, enabling clean dependency injection patterns.
version: 0.1.1
repository: https://github.com/robert-northmind/dartypod

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.24.0
